version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-ufc-api
    depends_on:
      - symfony
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public

  symfony:
    hostname: ufc-api
    container_name: ufc-api
    build:
      context: ./docker/symfony
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:rootpwd@db:3306/ufc-api
    volumes:
      - .:/app

  db:
    image: mariadb:latest
    container_name: db-ufc-api
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_DATABASE: "ufc-api"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: {}